### ISSUE TITLE
Exception when setting tags to servers

### ISSUE THREAD

**Issue by neubi4** [opentelekomcloud/ansible-collection-cloud#234]
I am trying to set tags on a server using the tag module:
```
- name: Set Tags on instance
  opentelekomcloud.cloud.tag:
    server: "{{ vm_name }}"
    state: present
    tags:
      - sometag
    mode: replace
```

This does not work, i am getting an error:
```
TASK [noc.domon-master-vm-otc : Set Tags on instance] ******************************************************************************************************************************************************************************************************
Tuesday 15 November 2022  08:32:04 +0100 (0:00:00.019)       0:00:07.427 ******
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: TypeError: fetch_tags() takes 4 positional arguments but 6 were given
fatal: [domon-live]: FAILED! => changed=false
  module_stderr: |-
    Traceback (most recent call last):
      File "/home/nux/.ansible/tmp/ansible-tmp-1668497525.0074553-17032-212707592718055/AnsiballZ_tag.py", line 107, in <module>
        _ansiballz_main()
      File "/home/nux/.ansible/tmp/ansible-tmp-1668497525.0074553-17032-212707592718055/AnsiballZ_tag.py", line 99, in _ansiballz_main
        invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
      File "/home/nux/.ansible/tmp/ansible-tmp-1668497525.0074553-17032-212707592718055/AnsiballZ_tag.py", line 47, in invoke_module
        runpy.run_module(mod_name='ansible_collections.opentelekomcloud.cloud.plugins.modules.tag', init_globals=dict(_module_fqn='ansible_collections.opentelekomcloud.cloud.plugins.modules.tag', _modlib_path=modlib_path),
      File "/usr/lib/python3.9/runpy.py", line 210, in run_module
        return _run_module_code(code, init_globals, run_name, mod_spec)
      File "/usr/lib/python3.9/runpy.py", line 97, in _run_module_code
        _run_code(code, mod_globals, init_globals,
      File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
        exec(code, run_globals)
      File "/tmp/ansible_opentelekomcloud.cloud.tag_payload_xo1pglz1/ansible_opentelekomcloud.cloud.tag_payload.zip/ansible_collections/opentelekomcloud/cloud/plugins/modules/tag.py", line 365, in <module>
      File "/tmp/ansible_opentelekomcloud.cloud.tag_payload_xo1pglz1/ansible_opentelekomcloud.cloud.tag_payload.zip/ansible_collections/opentelekomcloud/cloud/plugins/modules/tag.py", line 361, in main
    sible_opentelekomcloud.cloud.tag_payload_xo1pglz1/ansible_opentelekomcloud.cloud.tag_payload.zip/ansible_collections/opentelekomcloud/cloud/plugins/module_utils/otc.py", line 201, in __call__
      File "/tmp/ansible_opentelekomcloud.cloud.tag_payload_xo1pglz1/ansible_opentelekomcloud.cloud.tag_payload.zip/ansible_collections/opentelekomcloud/cloud/plugins/modules/tag.py", line 318, in run
    TypeError: fetch_tags() takes 4 positional arguments but 6 were given
  module_stdout: ''
  msg: |-
    MODULE FAILURE
    See stdout/stderr for the exact error
  rc: 1
```

Used Python Modules:
```
otcextensions==0.26.3
openstacksdk==0.61.0
python-openstackclient==6.0.0
```

Used Collections:
```
collections:
  - name: openstack.cloud
    version: 1.10.0
  - name: opentelekomcloud.cloud
    version: 0.12.4
```

Is there a bug in the tag module? I did have a look at the code, but could not find the line where fetch_tags() is called with too many arguments...

Also it seems like the exaples in [plugins/modules/tag.py#L91](https://github.com/opentelekomcloud/ansible-collection-cloud/blob/master/plugins/modules/tag.py#L91) are wrong, they suggest to use `opentelekomcloud.cloud.os_tag` which does not exist, it should be `opentelekomcloud.cloud.tag`. I can fix the examples when we get the tag module to work for us.

**Comment by Polina-Gubina** [comment]
Hi @neubi4 ! yes, it seems to be a bug so i am checking now and let you now soon!
