### ISSUE TITLE
Deletion of LB is not working

### ISSUE THREAD

**Issue by hadoopch** [opentelekomcloud/ansible-collection-cloud#279]
Hi all,

today it tried to create and delete a ELB.
Creation of loadbalancer worked fine , but when i tried to delete the LB i got the following error:

```
The full traceback is:
Traceback (most recent call last):
  File "/home/linux/.ansible/tmp/ansible-tmp-1687509906.1862547-1000-129926501526192/AnsiballZ_loadbalancer.py", line 107, in <module>
    _ansiballz_main()
  File "/home/linux/.ansible/tmp/ansible-tmp-1687509906.1862547-1000-129926501526192/AnsiballZ_loadbalancer.py", line 99, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/linux/.ansible/tmp/ansible-tmp-1687509906.1862547-1000-129926501526192/AnsiballZ_loadbalancer.py", line 47, in invoke_module
    runpy.run_module(mod_name='ansible_collections.opentelekomcloud.cloud.plugins.modules.loadbalancer', init_globals=dict(_module_fqn='ansible_collections.opentelekomcloud.cloud.plugins.modules.loadbalancer', _modlib_path=modlib_path),
  File "/usr/local/lib/python3.8/runpy.py", line 206, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/local/lib/python3.8/runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/local/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_opentelekomcloud.cloud.loadbalancer_payload_ieg_0ke6/ansible_opentelekomcloud.cloud.loadbalancer_payload.zip/ansible_collections/opentelekomcloud/cloud/plugins/modules/loadbalancer.py", line 384, in <module>
  File "/tmp/ansible_opentelekomcloud.cloud.loadbalancer_payload_ieg_0ke6/ansible_opentelekomcloud.cloud.loadbalancer_payload.zip/ansible_collections/opentelekomcloud/cloud/plugins/modules/loadbalancer.py", line 380, in main
  File "/tmp/ansible_opentelekomcloud.cloud.loadbalancer_payload_ieg_0ke6/ansible_opentelekomcloud.cloud.loadbalancer_payload.zip/ansible_collections/opentelekomcloud/cloud/plugins/module_utils/otc.py", line 215, in __call__
  File "/tmp/ansible_opentelekomcloud.cloud.loadbalancer_payload_ieg_0ke6/ansible_opentelekomcloud.cloud.loadbalancer_payload.zip/ansible_collections/opentelekomcloud/cloud/plugins/modules/loadbalancer.py", line 367, in run
AttributeError: 'Proxy' object has no attribute 'delete_loadbalancer'
fatal: [localhost]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/home/linux/.ansible/tmp/ansible-tmp-1687509906.1862547-1000-129926501526192/AnsiballZ_loadbalancer.py\", line 107, in <module>\n    _ansiballz_main()\n  File \"/home/linux/.ansible/tmp/ansible-tmp-1687509906.1862547-1000-129926501526192/AnsiballZ_loadbalancer.py\", line 99, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/linux/.ansible/tmp/ansible-tmp-1687509906.1862547-1000-129926501526192/AnsiballZ_loadbalancer.py\", line 47, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.opentelekomcloud.cloud.plugins.modules.loadbalancer', init_globals=dict(_module_fqn='ansible_collections.opentelekomcloud.cloud.plugins.modules.loadbalancer', _modlib_path=modlib_path),\n  File \"/usr/local/lib/python3.8/runpy.py\", line 206, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/local/lib/python3.8/runpy.py\", line 96, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/local/lib/python3.8/runpy.py\", line 86, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_opentelekomcloud.cloud.loadbalancer_payload_ieg_0ke6/ansible_opentelekomcloud.cloud.loadbalancer_payload.zip/ansible_collections/opentelekomcloud/cloud/plugins/modules/loadbalancer.py\", line 384, in <module>\n  File \"/tmp/ansible_opentelekomcloud.cloud.loadbalancer_payload_ieg_0ke6/ansible_opentelekomcloud.cloud.loadbalancer_payload.zip/ansible_collections/opentelekomcloud/cloud/plugins/modules/loadbalancer.py\", line 380, in main\n  File \"/tmp/ansible_opentelekomcloud.cloud.loadbalancer_payload_ieg_0ke6/ansible_opentelekomcloud.cloud.loadbalancer_payload.zip/ansible_collections/opentelekomcloud/cloud/plugins/module_utils/otc.py\", line 215, in __call__\n  File \"/tmp/ansible_opentelekomcloud.cloud.loadbalancer_payload_ieg_0ke6/ansible_opentelekomcloud.cloud.loadbalancer_payload.zip/ansible_collections/opentelekomcloud/cloud/plugins/modules/loadbalancer.py\", line 367, in run\nAttributeError: 'Proxy' object has no attribute 'delete_loadbalancer'\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}
````

Playbook was :

```
- opentelekomcloud.cloud.loadbalancer:
            state: absent
            name:  cdp-ELB-ext
            delete_public_ip: yes
```

**Comment by Polina-Gubina** [comment]
Hi @hadoopch ! do you have installed otcextensions?

**Comment by hadoopch** [comment]
Hi Polina,

yes  it is installed. 
Rgds
Uli

**Comment by Polina-Gubina** [comment]
@hadoopch which version?
rgds

**Comment by hadoopch** [comment]
Hi Polina,

thank you !!!
I had 0.26.3 installed. I made an update to 0.30.2. Also sdk was updated.
 Now it is working !!!
Could you be so kind a check my latest issue on otc extension -if you have time
otc loadbalancer list is  not working for any reason.

**Comment by Polina-Gubina** [comment]
@hadoopch it is cool;) yes, of course, i will try to figure out where problem is, always glad to help ;)

**Comment by hadoopch** [comment]
Thanks
